In [3]:
import pandas as pd
import numpy as np

###### Creating a dataframe from an array

In [8]:
# creating an array
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# creating a dataframe
df = pd.DataFrame(data)
df

   0  1
0  1  2
1  3  4
2  5  6

In [9]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
                 columns=['col1', 'col2'])
df

      col1  col2
row1     1     2
row2     3     4
row3     5     6

In [12]:
# creating an array with list shape
data = [[1, 2], [3, 4], [5, 6]]
data

[[1, 2], [3, 4], [5, 6]]

In [13]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'],
                 columns=['col1', 'col2'])
df

      col1  col2
row1     1     2
row2     3     4
row3     5     6

###### Creating a DataFrame from a dictionary

In [15]:
# Creating a DataFrame from a dictionary
states = ["California", "Texas", "Florida", "New York"]
population = [39613493, 29730311, 21944577, 19299981]

In [16]:
# Storing lists within a dictionary
dict_states = {'States': states, 'Population': population}

In [ ]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)
# df_population = pd.DataFrame.from_dict(dict_states)
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

###### Creating a DataFrame from a csv file

In [7]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86